### PR TITLE
upload of the missing mutable Integer wrapper class IntWrapper.java

### PR DESCRIPTION
**Pull request by cklimkowski**

### CODE REVIEW

**Comment by muhammadkarbalaee** [comment]
What is the point of this intWrapper class? why should an Integer be wrapped? can you please explain?

**Comment by cklimkowski** [comment]
When I used the sole Integer in getSorted function it did not preserve changing its value.
For explanation please look into https://www.geeksforgeeks.org/how-to-pass-integer-by-reference-in-java/

**Comment by mayur-ravindram** [comment]
Verified in my local and compilation issue is resolved. Can we approve this and merge to development branch?
@muhammadkarbalaee

**Review by muhammadkarbalaee — APPROVED** [review]

**Comment by cklimkowski** [comment]
Thank you for the approval and merge, I am pleased with that :)

**Pull request merged**
