### PR TITLE
Bubble Sort : Enhancement

### LINKED ISSUE #66: Bubble Sort implementation is not most efficient
The current implementation of bubble sort goes from first index to last index in every loop. As each loop in Bubble Sort shifts the largest element to right there is no need to check for already sorted array on right side. [https://github.com/muhammadkarbalaee/jalgorithm/blob/e6bd6b2121c46f427f464097c3760b7456f04b80/src/main/java/io/github/jalgorithm/algorithms/sorts/BubbleSort.java#L45](url)

### PR DESCRIPTION
**Pull request by Hreshi**
Fixes #66 Bubble sort implementation 
Code tested on  bubble sort problem [https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjrp_SByqH1AhVRJaYKHUI3AYoQFnoECAYQAQ&url=https%3A%2F%2Fpractice.geeksforgeeks.org%2Fproblems%2Fbubble-sort%2F1&usg=AOvVaw2tGdjJoJslqL5jRxItyvvA](url)

### CODE REVIEW

**Review by muhammadkarbalaee — COMMENTED** [review]
Your additions are completely valid, but why did you delete the isSorted flag? it doesn't have any collision with your enhancement.

**Comment by Hreshi** [comment]
> Your additions are completely valid, but why did you delete the isSorted flag? it doesn't have any collision with your enhancement.

Let me explain the code in detail
consider an array -> 1 2 3 4 3 2 1 1   5 6 7 8 9 19
prevSwap points to the latest element that was swap
end points to the right limit
in each outer loop i am making prevSwap = 0 and if there is no swap or only first element is swapped then prevSwap will remain 0. after the loop ends i am assigning end = prevSwap and there is a condition in outer loop end != 0. So these two variables are reused as isSorted flag.
Also we can add sort(left index, right index) method to sort a specified partition , there we just need to change 0 to left and end to right

**Comment by muhammadkarbalaee** [comment]
Nice. so can you please add another method in this class which gets two inputs which is able to sort only and specified part? 
keep this sort()
and add 
sort(leftIndex,rightIndex) 
below it. it is a good feature. 

and It would be so good if you comment before this new sort function and explain it.
i think you know how

/**
your explanation here
*/

**Comment by Hreshi** [comment]
There was some problem so i pushed in my branch. Next time i will take care. Can you review the changes

**Comment by muhammadkarbalaee** [comment]
That is nice. thanks for this effective improvement. merged.

**Pull request merged**
